#!/usr/bin/env python3
"""Organize master-cyber-skills by cyber function category."""

import os
import subprocess
import sys

SKILLS_DIR = "skills"

# Category mapping: skill-folder-name -> category
MAPPING = {
    # ─── OFFENSIVE ───────────────────────────────────────────────────
    "exploit-development": "offensive",
    "exploiting-active-directory-certificate-services-esc1": "offensive",
    "exploiting-active-directory-with-bloodhound": "offensive",
    "exploiting-api-injection-vulnerabilities": "offensive",
    "exploiting-bgp-hijacking-vulnerabilities": "offensive",
    "exploiting-broken-function-level-authorization": "offensive",
    "exploiting-broken-link-hijacking": "offensive",
    "exploiting-constrained-delegation-abuse": "offensive",
    "exploiting-deeplink-vulnerabilities": "offensive",
    "exploiting-excessive-data-exposure-in-api": "offensive",
    "exploiting-http-request-smuggling": "offensive",
    "exploiting-idor-vulnerabilities": "offensive",
    "exploiting-insecure-data-storage-in-mobile": "offensive",
    "exploiting-insecure-deserialization": "offensive",
    "exploiting-ipv6-vulnerabilities": "offensive",
    "exploiting-jwt-algorithm-confusion-attack": "offensive",
    "exploiting-kerberoasting-with-impacket": "offensive",
    "exploiting-mass-assignment-in-rest-apis": "offensive",
    "exploiting-ms17-010-eternalblue-vulnerability": "offensive",
    "exploiting-nopac-cve-2021-42278-42287": "offensive",
    "exploiting-nosql-injection-vulnerabilities": "offensive",
    "exploiting-oauth-misconfiguration": "offensive",
    "exploiting-prototype-pollution-in-javascript": "offensive",
    "exploiting-race-condition-vulnerabilities": "offensive",
    "exploiting-server-side-request-forgery": "offensive",
    "exploiting-smb-vulnerabilities-with-metasploit": "offensive",
    "exploiting-sql-injection-vulnerabilities": "offensive",
    "exploiting-sql-injection-with-sqlmap": "offensive",
    "exploiting-template-injection-vulnerabilities": "offensive",
    "exploiting-type-juggling-vulnerabilities": "offensive",
    "exploiting-vulnerabilities-with-metasploit-framework": "offensive",
    "exploiting-websocket-vulnerabilities": "offensive",
    "exploiting-zerologon-vulnerability-cve-2020-1472": "offensive",
    "building-c2-infrastructure-with-sliver-framework": "offensive",
    "building-red-team-c2-infrastructure-with-havoc": "offensive",
    "conducting-domain-persistence-with-dcsync": "offensive",
    "conducting-full-scope-red-team-engagement": "offensive",
    "conducting-man-in-the-middle-attack-simulation": "offensive",
    "conducting-pass-the-ticket-attack": "offensive",
    "executing-active-directory-attack-simulation": "offensive",
    "executing-red-team-engagement-planning": "offensive",
    "executing-red-team-exercise": "offensive",
    "performing-arp-spoofing-attack-simulation": "offensive",
    "performing-bandwidth-throttling-attack-simulation": "offensive",
    "performing-blind-ssrf-exploitation": "offensive",
    "performing-clickjacking-attack-test": "offensive",
    "performing-content-security-policy-bypass": "offensive",
    "performing-credential-access-with-lazagne": "offensive",
    "performing-csrf-attack-simulation": "offensive",
    "performing-directory-traversal-testing": "offensive",
    "performing-graphql-depth-limit-attack": "offensive",
    "performing-graphql-introspection-attack": "offensive",
    "performing-hash-cracking-with-hashcat": "offensive",
    "performing-http-parameter-pollution-attack": "offensive",
    "performing-initial-access-with-evilginx3": "offensive",
    "performing-jwt-none-algorithm-attack": "offensive",
    "performing-kerberoasting-attack": "offensive",
    "performing-lateral-movement-with-wmiexec": "offensive",
    "performing-packet-injection-attack": "offensive",
    "performing-privilege-escalation-assessment": "offensive",
    "performing-privilege-escalation-on-linux": "offensive",
    "performing-second-order-sql-injection": "offensive",
    "performing-ssl-stripping-attack": "offensive",
    "performing-vlan-hopping-attack": "offensive",
    "performing-web-application-firewall-bypass": "offensive",
    "performing-web-cache-deception-attack": "offensive",
    "performing-web-cache-poisoning-attack": "offensive",
    "performing-wifi-password-cracking-with-aircrack": "offensive",
    "stealth-techniques": "offensive",
    "using-payload-library": "offensive",
    "bypassing-authentication-with-forced-browsing": "offensive",
    "conducting-adversary-in-the-middle-attack": "offensive",
    "ctf-pwn": "offensive",
    "ctf-web": "offensive",
    "ctf-crypto": "offensive",
    "ctf-misc": "offensive",
    "ctf-reverse": "offensive",
    "ctf-forensics": "offensive",
    "ctf-malware": "offensive",
    "ctf-osint": "offensive",
    "solve-challenge": "offensive",
    "wooyun-legacy": "offensive",
    "using-superhackers": "offensive",
    "performing-privileged-account-discovery": "offensive",

    # ─── RECONNAISSANCE ──────────────────────────────────────────────
    "recon-and-enumeration": "reconnaissance",
    "collecting-indicators-of-compromise": "reconnaissance",
    "collecting-open-source-intelligence": "reconnaissance",
    "conducting-external-reconnaissance-with-osint": "reconnaissance",
    "conducting-internal-reconnaissance-with-bloodhound-ce": "reconnaissance",
    "performing-open-source-intelligence-gathering": "reconnaissance",
    "performing-subdomain-enumeration-with-subfinder": "reconnaissance",
    "performing-dns-enumeration-and-zone-transfer": "reconnaissance",
    "performing-brand-monitoring-for-impersonation": "reconnaissance",
    "performing-dark-web-monitoring-for-threats": "reconnaissance",
    "performing-ip-reputation-analysis-with-shodan": "reconnaissance",
    "performing-paste-site-monitoring-for-credentials": "reconnaissance",
    "performing-api-inventory-and-discovery": "reconnaissance",
    "scanning-network-with-nmap-advanced": "reconnaissance",
    "building-threat-actor-profile-from-osint": "reconnaissance",
    "monitoring-darkweb-sources": "reconnaissance",

    # ─── DETECTION ───────────────────────────────────────────────────
    "detecting-anomalous-authentication-patterns": "detection",
    "detecting-api-enumeration-attacks": "detection",
    "detecting-arp-poisoning-in-network-traffic": "detection",
    "detecting-aws-credential-exposure-with-trufflehog": "detection",
    "detecting-aws-guardduty-findings-automation": "detection",
    "detecting-azure-service-principal-abuse": "detection",
    "detecting-broken-object-property-level-authorization": "detection",
    "detecting-business-email-compromise": "detection",
    "detecting-business-email-compromise-with-ai": "detection",
    "detecting-cloud-cryptomining-activity": "detection",
    "detecting-cloud-threats-with-guardduty": "detection",
    "detecting-compromised-cloud-credentials": "detection",
    "detecting-container-drift-at-runtime": "detection",
    "detecting-container-escape-attempts": "detection",
    "detecting-container-escape-with-falco-rules": "detection",
    "detecting-credential-dumping-with-edr": "detection",
    "detecting-cryptomining-in-cloud": "detection",
    "detecting-dcsync-attack-in-active-directory": "detection",
    "detecting-dll-sideloading-attacks": "detection",
    "detecting-dnp3-protocol-anomalies": "detection",
    "detecting-dns-exfiltration-with-dns-query-analysis": "detection",
    "detecting-email-forwarding-rules-attack": "detection",
    "detecting-evasion-techniques-in-endpoint-logs": "detection",
    "detecting-fileless-attacks-on-endpoints": "detection",
    "detecting-fileless-malware-techniques": "detection",
    "detecting-golden-ticket-attacks-in-kerberos-logs": "detection",
    "detecting-insider-threat-behaviors": "detection",
    "detecting-kerberoasting-attacks": "detection",
    "detecting-lateral-movement-in-network": "detection",
    "detecting-lateral-movement-with-splunk": "detection",
    "detecting-mimikatz-execution-patterns": "detection",
    "detecting-misconfigured-azure-storage": "detection",
    "detecting-mobile-malware-behavior": "detection",
    "detecting-modbus-command-injection-attacks": "detection",
    "detecting-modbus-protocol-anomalies": "detection",
    "detecting-network-anomalies-with-zeek": "detection",
    "detecting-network-scanning-with-ids-signatures": "detection",
    "detecting-pass-the-hash-attacks": "detection",
    "detecting-port-scanning-with-fail2ban": "detection",
    "detecting-privilege-escalation-attempts": "detection",
    "detecting-privilege-escalation-in-kubernetes-pods": "detection",
    "detecting-process-hollowing-technique": "detection",
    "detecting-process-injection-techniques": "detection",
    "detecting-qr-code-phishing-with-email-security": "detection",
    "detecting-ransomware-precursors-in-network": "detection",
    "detecting-rootkit-activity": "detection",
    "detecting-s3-data-exfiltration-attempts": "detection",
    "detecting-service-account-abuse": "detection",
    "detecting-shadow-api-endpoints": "detection",
    "detecting-spearphishing-with-email-gateway": "detection",
    "detecting-suspicious-powershell-execution": "detection",
    "detecting-t1003-credential-dumping-with-edr": "detection",
    "detecting-t1055-process-injection-with-sysmon": "detection",
    "detecting-t1548-abuse-elevation-control-mechanism": "detection",
    "building-detection-rule-with-splunk-spl": "detection",
    "building-detection-rules-with-sigma": "detection",
    "configuring-windows-event-logging-for-detection": "detection",
    "implementing-siem-use-cases-for-detection": "detection",
    "implementing-alert-fatigue-reduction": "detection",
    "performing-alert-triage-with-elastic-siem": "detection",
    "performing-false-positive-reduction-in-siem": "detection",
    "performing-log-source-onboarding-in-siem": "detection",
    "correlating-security-events-in-qradar": "detection",
    "triaging-security-alerts-in-splunk": "detection",
    "implementing-mitre-attack-coverage-mapping": "detection",
    "configuring-snort-ids-for-intrusion-detection": "detection",
    "configuring-suricata-for-network-monitoring": "detection",
    "configuring-host-based-intrusion-detection": "detection",
    "deploying-osquery-for-endpoint-monitoring": "detection",
    "deploying-edr-agent-with-crowdstrike": "detection",
    "implementing-honeypot-for-ransomware-detection": "detection",
    "analyzing-security-logs-with-splunk": "detection",
    "analyzing-windows-event-logs-in-splunk": "detection",
    "performing-user-behavior-analytics": "detection",
    "building-cloud-siem-with-sentinel": "detection",
    "detecting-anomalies-in-industrial-control-systems": "detection",
    "detecting-attacks-on-historian-servers": "detection",
    "detecting-attacks-on-scada-systems": "detection",
    "detecting-stuxnet-style-attacks": "detection",
    "performing-lateral-movement-detection": "detection",

    # ─── THREAT HUNTING ──────────────────────────────────────────────
    "hunting-advanced-persistent-threats": "threat-hunting",
    "hunting-for-beaconing-with-frequency-analysis": "threat-hunting",
    "hunting-for-command-and-control-beaconing": "threat-hunting",
    "hunting-for-data-exfiltration-indicators": "threat-hunting",
    "hunting-for-dns-tunneling-with-zeek": "threat-hunting",
    "hunting-for-living-off-the-cloud-techniques": "threat-hunting",
    "hunting-for-living-off-the-land-binaries": "threat-hunting",
    "hunting-for-lolbins-execution-in-endpoint-logs": "threat-hunting",
    "hunting-for-persistence-mechanisms-in-windows": "threat-hunting",
    "hunting-for-persistence-via-wmi-subscriptions": "threat-hunting",
    "hunting-for-registry-persistence-mechanisms": "threat-hunting",
    "hunting-for-scheduled-task-persistence": "threat-hunting",
    "hunting-for-shadow-copy-deletion": "threat-hunting",
    "hunting-for-spearphishing-indicators": "threat-hunting",
    "hunting-for-supply-chain-compromise": "threat-hunting",
    "hunting-for-suspicious-scheduled-tasks": "threat-hunting",
    "hunting-for-unusual-network-connections": "threat-hunting",
    "hunting-for-webshell-activity": "threat-hunting",
    "performing-threat-hunting-with-elastic-siem": "threat-hunting",
    "building-threat-hunt-hypothesis-framework": "threat-hunting",

    # ─── INCIDENT RESPONSE ───────────────────────────────────────────
    "incident-response": "incident-response",
    "conducting-cloud-incident-response": "incident-response",
    "conducting-malware-incident-response": "incident-response",
    "conducting-phishing-incident-response": "incident-response",
    "conducting-post-incident-lessons-learned": "incident-response",
    "eradicating-malware-from-infected-systems": "incident-response",
    "recovering-from-ransomware-attack": "incident-response",
    "performing-ransomware-incident-response": "incident-response",
    "performing-ransomware-response": "incident-response",
    "performing-ransomware-tabletop-exercise": "incident-response",
    "performing-soc-tabletop-exercise": "incident-response",
    "performing-purple-team-exercise": "incident-response",
    "performing-cloud-incident-containment-procedures": "incident-response",
    "triaging-security-incident": "incident-response",
    "triaging-security-incident-with-ir-playbook": "incident-response",
    "containing-active-breach": "incident-response",
    "containing-active-security-breach": "incident-response",
    "building-incident-response-playbook": "incident-response",
    "building-incident-response-dashboard": "incident-response",
    "building-malware-incident-communication-template": "incident-response",
    "building-soc-playbook-for-ransomware": "incident-response",
    "building-soc-escalation-matrix": "incident-response",
    "building-soc-metrics-and-kpi-tracking": "incident-response",
    "implementing-ticketing-system-for-incidents": "incident-response",
    "implementing-velociraptor-for-ir-collection": "incident-response",
    "implementing-soar-automation-with-phantom": "incident-response",
    "implementing-soar-playbook-with-palo-alto-xsoar": "incident-response",
    "investigating-insider-threat-indicators": "incident-response",
    "investigating-phishing-email-incident": "incident-response",
    "investigating-ransomware-attack-artifacts": "incident-response",
    "performing-insider-threat-investigation": "incident-response",
    "building-phishing-reporting-button-workflow": "incident-response",
    "collecting-volatile-evidence-from-compromised-host": "incident-response",
    "conducting-malware-incident-response": "incident-response",

    # ─── FORENSICS ───────────────────────────────────────────────────
    "acquiring-disk-image-with-dd-and-dcfldd": "forensics",
    "analyzing-browser-forensics-with-hindsight": "forensics",
    "analyzing-disk-image-with-autopsy": "forensics",
    "analyzing-linux-system-artifacts": "forensics",
    "analyzing-lnk-file-and-jump-list-artifacts": "forensics",
    "analyzing-mft-for-deleted-file-recovery": "forensics",
    "analyzing-memory-dumps-with-volatility": "forensics",
    "analyzing-network-traffic-for-incidents": "forensics",
    "analyzing-network-traffic-with-wireshark": "forensics",
    "analyzing-outlook-pst-for-email-forensics": "forensics",
    "analyzing-prefetch-files-for-execution-history": "forensics",
    "analyzing-slack-space-and-file-system-artifacts": "forensics",
    "analyzing-usb-device-connection-history": "forensics",
    "analyzing-windows-lnk-files-for-artifacts": "forensics",
    "analyzing-windows-registry-for-artifacts": "forensics",
    "analyzing-windows-shellbag-artifacts": "forensics",
    "building-incident-timeline-with-timesketch": "forensics",
    "conducting-memory-forensics-with-volatility": "forensics",
    "extracting-browser-history-artifacts": "forensics",
    "extracting-windows-event-logs-artifacts": "forensics",
    "performing-cloud-forensics-investigation": "forensics",
    "performing-cloud-storage-forensic-acquisition": "forensics",
    "performing-disk-forensics-investigation": "forensics",
    "performing-endpoint-forensics-investigation": "forensics",
    "performing-file-carving-with-foremost": "forensics",
    "performing-linux-log-forensics-investigation": "forensics",
    "performing-log-analysis-for-forensic-investigation": "forensics",
    "performing-memory-forensics-with-volatility3": "forensics",
    "performing-memory-forensics-with-volatility3-plugins": "forensics",
    "performing-mobile-device-forensics-with-cellebrite": "forensics",
    "performing-network-forensics-with-wireshark": "forensics",
    "performing-network-packet-capture-analysis": "forensics",
    "performing-network-traffic-analysis-with-zeek": "forensics",
    "performing-sqlite-database-forensics": "forensics",
    "performing-steganography-detection": "forensics",
    "performing-timeline-reconstruction-with-plaso": "forensics",
    "performing-windows-artifact-analysis-with-eric-zimmerman-tools": "forensics",
    "recovering-deleted-files-with-photorec": "forensics",
    "analyzing-docker-container-forensics": "forensics",
    "extracting-credentials-from-memory-dump": "forensics",

    # ─── MALWARE ANALYSIS ────────────────────────────────────────────
    "analyzing-apt-group-with-mitre-navigator": "malware-analysis",
    "analyzing-bootkit-and-rootkit-samples": "malware-analysis",
    "analyzing-cobalt-strike-beacon-configuration": "malware-analysis",
    "analyzing-command-and-control-communication": "malware-analysis",
    "analyzing-dns-logs-for-exfiltration": "malware-analysis",
    "analyzing-email-headers-for-phishing-investigation": "malware-analysis",
    "analyzing-golang-malware-with-ghidra": "malware-analysis",
    "analyzing-indicators-of-compromise": "malware-analysis",
    "analyzing-linux-elf-malware": "malware-analysis",
    "analyzing-macro-malware-in-office-documents": "malware-analysis",
    "analyzing-malicious-url-with-urlscan": "malware-analysis",
    "analyzing-malware-behavior-with-cuckoo-sandbox": "malware-analysis",
    "analyzing-malware-family-relationships-with-malpedia": "malware-analysis",
    "analyzing-malware-persistence-with-autoruns": "malware-analysis",
    "analyzing-network-covert-channels-in-malware": "malware-analysis",
    "analyzing-network-traffic-of-malware": "malware-analysis",
    "analyzing-packed-malware-with-upx-unpacker": "malware-analysis",
    "analyzing-pdf-malware-with-pdfid": "malware-analysis",
    "analyzing-phishing-email-headers": "malware-analysis",
    "analyzing-ransomware-encryption-mechanisms": "malware-analysis",
    "analyzing-supply-chain-malware-artifacts": "malware-analysis",
    "building-automated-malware-submission-pipeline": "malware-analysis",
    "building-ioc-defanging-and-sharing-pipeline": "malware-analysis",
    "deobfuscating-javascript-malware": "malware-analysis",
    "deobfuscating-powershell-obfuscated-malware": "malware-analysis",
    "extracting-config-from-agent-tesla-rat": "malware-analysis",
    "extracting-iocs-from-malware-samples": "malware-analysis",
    "performing-automated-malware-analysis-with-cape": "malware-analysis",
    "performing-dynamic-analysis-with-any-run": "malware-analysis",
    "performing-firmware-malware-analysis": "malware-analysis",
    "performing-malware-hash-enrichment-with-virustotal": "malware-analysis",
    "performing-malware-ioc-extraction": "malware-analysis",
    "performing-malware-persistence-investigation": "malware-analysis",
    "performing-malware-triage-with-yara": "malware-analysis",
    "performing-static-malware-analysis-with-pe-studio": "malware-analysis",
    "reverse-engineering-android-malware-with-jadx": "malware-analysis",
    "reverse-engineering-dotnet-malware-with-dnspy": "malware-analysis",
    "reverse-engineering-ios-app-with-frida": "malware-analysis",
    "reverse-engineering-malware-with-ghidra": "malware-analysis",
    "reverse-engineering-ransomware-encryption-routine": "malware-analysis",
    "reverse-engineering-rust-malware": "malware-analysis",
    "yara-rule-authoring": "malware-analysis",
    "performing-yara-rule-development-for-detection": "malware-analysis",
    "ghidra-headless": "malware-analysis",
    "dwarf-expert": "malware-analysis",
    "analyzing-ios-app-security-with-objection": "malware-analysis",
    "performing-plc-firmware-security-analysis": "malware-analysis",
    "analyzing-ransomware-leak-site-intelligence": "malware-analysis",

    # ─── VULNERABILITY MANAGEMENT ────────────────────────────────────
    "building-vulnerability-aging-and-sla-tracking": "vulnerability-management",
    "building-vulnerability-dashboard-with-defectdojo": "vulnerability-management",
    "building-vulnerability-exception-tracking-system": "vulnerability-management",
    "building-vulnerability-scanning-workflow": "vulnerability-management",
    "building-patch-tuesday-response-process": "vulnerability-management",
    "implementing-epss-score-for-vulnerability-prioritization": "vulnerability-management",
    "implementing-patch-management-workflow": "vulnerability-management",
    "implementing-rapid7-insightvm-for-scanning": "vulnerability-management",
    "implementing-vulnerability-remediation-sla": "vulnerability-management",
    "implementing-vulnerability-sla-breach-alerting": "vulnerability-management",
    "performing-agentless-vulnerability-scanning": "vulnerability-management",
    "performing-asset-criticality-scoring-for-vulns": "vulnerability-management",
    "performing-authenticated-scan-with-openvas": "vulnerability-management",
    "performing-authenticated-vulnerability-scan": "vulnerability-management",
    "performing-cve-prioritization-with-kev-catalog": "vulnerability-management",
    "performing-endpoint-vulnerability-remediation": "vulnerability-management",
    "performing-vulnerability-scanning-with-nessus": "vulnerability-management",
    "performing-web-application-vulnerability-triage": "vulnerability-management",
    "prioritizing-vulnerabilities-with-cvss-scoring": "vulnerability-management",
    "scanning-infrastructure-with-nessus": "vulnerability-management",
    "triaging-vulnerabilities-with-ssvc-framework": "vulnerability-management",
    "triage-vuln": "vulnerability-management",
    "vulnerability-scanning": "vulnerability-management",
    "implementing-attack-path-analysis-with-xm-cyber": "vulnerability-management",
    "implementing-continuous-security-validation-with-bas": "vulnerability-management",

    # ─── PENETRATION TESTING ─────────────────────────────────────────
    "android-pentesting": "penetration-testing",
    "api-pentesting": "penetration-testing",
    "conducting-api-security-testing": "penetration-testing",
    "conducting-cloud-infrastructure-penetration-test": "penetration-testing",
    "conducting-cloud-penetration-testing": "penetration-testing",
    "conducting-internal-network-penetration-test": "penetration-testing",
    "conducting-mobile-app-penetration-test": "penetration-testing",
    "conducting-mobile-application-penetration-test": "penetration-testing",
    "conducting-network-penetration-test": "penetration-testing",
    "conducting-wireless-network-penetration-test": "penetration-testing",
    "finishing-an-engagement": "penetration-testing",
    "infra-pentesting": "penetration-testing",
    "intercepting-mobile-traffic-with-burpsuite": "penetration-testing",
    "penetration-testing": "penetration-testing",
    "pentest-start": "penetration-testing",
    "performing-active-directory-penetration-test": "penetration-testing",
    "performing-active-directory-vulnerability-assessment": "penetration-testing",
    "performing-active-directory-bloodhound-analysis": "penetration-testing",
    "performing-active-directory-compromise-investigation": "penetration-testing",
    "performing-api-security-testing-with-postman": "penetration-testing",
    "performing-aws-privilege-escalation-assessment": "penetration-testing",
    "performing-cloud-penetration-testing": "penetration-testing",
    "performing-cloud-penetration-testing-with-pacu": "penetration-testing",
    "performing-external-network-penetration-test": "penetration-testing",
    "performing-iot-security-assessment": "penetration-testing",
    "performing-kubernetes-penetration-testing": "penetration-testing",
    "performing-physical-intrusion-assessment": "penetration-testing",
    "performing-thick-client-application-penetration-test": "penetration-testing",
    "performing-web-application-penetration-test": "penetration-testing",
    "performing-wireless-network-penetration-test": "penetration-testing",
    "performing-wireless-security-assessment-with-kismet": "penetration-testing",
    "scope-check": "penetration-testing",
    "webapp-pentesting": "penetration-testing",
    "performing-docker-bench-security-assessment": "penetration-testing",
    "performing-dynamic-analysis-of-android-app": "penetration-testing",
    "performing-android-app-static-analysis-with-mobsf": "penetration-testing",
    "performing-mobile-app-certificate-pinning-bypass": "penetration-testing",

    # ─── HARDENING ───────────────────────────────────────────────────
    "configuring-active-directory-tiered-model": "hardening",
    "configuring-ldap-security-hardening": "hardening",
    "configuring-windows-defender-advanced-settings": "hardening",
    "container-hardening": "hardening",
    "hardening-docker-containers-for-production": "hardening",
    "hardening-docker-daemon-configuration": "hardening",
    "hardening-linux-endpoint-with-cis-benchmark": "hardening",
    "hardening-windows-endpoint-with-cis-benchmark": "hardening",
    "implementing-application-whitelisting-with-applocker": "hardening",
    "implementing-memory-protection-with-dep-aslr": "hardening",
    "implementing-usb-device-control-policy": "hardening",
    "insecure-defaults": "hardening",
    "linux-hardening": "hardening",
    "windows-hardening": "hardening",
    "cis-benchmarks": "hardening",
    "auditing-cloud-with-cis-benchmarks": "hardening",
    "sharp-edges": "hardening",

    # ─── THREAT INTELLIGENCE ─────────────────────────────────────────
    "analyzing-campaign-attribution-evidence": "threat-intelligence",
    "analyzing-cyber-kill-chain": "threat-intelligence",
    "analyzing-threat-actor-ttps-with-mitre-attack": "threat-intelligence",
    "analyzing-threat-intelligence-feeds": "threat-intelligence",
    "analyzing-typosquatting-domains-with-dnstwist": "threat-intelligence",
    "analyzing-certificate-transparency-for-phishing": "threat-intelligence",
    "automating-ioc-enrichment": "threat-intelligence",
    "building-attack-pattern-library-from-cti-reports": "threat-intelligence",
    "building-ioc-enrichment-pipeline-with-opencti": "threat-intelligence",
    "building-threat-feed-aggregation-with-misp": "threat-intelligence",
    "building-threat-intelligence-enrichment-in-splunk": "threat-intelligence",
    "building-threat-intelligence-feed-integration": "threat-intelligence",
    "building-threat-intelligence-platform": "threat-intelligence",
    "collecting-threat-intelligence-with-misp": "threat-intelligence",
    "correlating-threat-campaigns": "threat-intelligence",
    "evaluating-threat-intelligence-platforms": "threat-intelligence",
    "ioc-lookup": "threat-intelligence",
    "implementing-stix-taxii-feed-integration": "threat-intelligence",
    "implementing-taxii-server-with-opentaxii": "threat-intelligence",
    "implementing-threat-intelligence-lifecycle-management": "threat-intelligence",
    "managing-intelligence-lifecycle": "threat-intelligence",
    "mapping-mitre-attack-techniques": "threat-intelligence",
    "mitre-map": "threat-intelligence",
    "performing-ioc-enrichment-automation": "threat-intelligence",
    "performing-indicator-lifecycle-management": "threat-intelligence",
    "performing-threat-landscape-assessment-for-sector": "threat-intelligence",
    "processing-stix-taxii-feeds": "threat-intelligence",
    "profiling-threat-actor-groups": "threat-intelligence",
    "tracking-threat-actor-infrastructure": "threat-intelligence",
    "executing-diamond-model-analysis": "threat-intelligence",
    "implementing-diamond-model-analysis": "threat-intelligence",
    "implementing-threat-modeling-with-mitre-attack": "threat-intelligence",
    "threat-modeling": "threat-intelligence",
    "performing-threat-modeling-with-owasp-threat-dragon": "threat-intelligence",

    # ─── CLOUD SECURITY ──────────────────────────────────────────────
    "auditing-aws-s3-bucket-permissions": "cloud-security",
    "auditing-azure-active-directory-configuration": "cloud-security",
    "auditing-gcp-iam-permissions": "cloud-security",
    "auditing-terraform-infrastructure-for-security": "cloud-security",
    "aws-cognito": "cloud-security",
    "aws-iam": "cloud-security",
    "aws-secrets-manager": "cloud-security",
    "aws-secrets-manager-itsmostafa": "cloud-security",
    "azure-keyvault": "cloud-security",
    "building-cloud-security-posture-management": "cloud-security",
    "configuring-aws-verified-access-for-ztna": "cloud-security",
    "deploying-cloudflare-access-for-zero-trust": "cloud-security",
    "deploying-palo-alto-prisma-access-zero-trust": "cloud-security",
    "gcp-secret-manager": "cloud-security",
    "implementing-aws-config-rules-for-compliance": "cloud-security",
    "implementing-aws-iam-permission-boundaries": "cloud-security",
    "implementing-aws-macie-for-data-classification": "cloud-security",
    "implementing-aws-security-hub": "cloud-security",
    "implementing-aws-security-hub-compliance": "cloud-security",
    "implementing-azure-ad-privileged-identity-management": "cloud-security",
    "implementing-azure-defender-for-cloud": "cloud-security",
    "implementing-cloud-dlp-for-data-protection": "cloud-security",
    "implementing-cloud-security-posture-management": "cloud-security",
    "implementing-cloud-trail-log-analysis": "cloud-security",
    "implementing-cloud-vulnerability-posture-management": "cloud-security",
    "implementing-cloud-waf-rules": "cloud-security",
    "implementing-gcp-binary-authorization": "cloud-security",
    "implementing-gcp-organization-policy-constraints": "cloud-security",
    "implementing-gcp-vpc-firewall-rules": "cloud-security",
    "performing-aws-account-enumeration-with-scout-suite": "cloud-security",
    "performing-cloud-asset-inventory-with-cartography": "cloud-security",
    "performing-gcp-security-assessment-with-forseti": "cloud-security",
    "remediating-s3-bucket-misconfiguration": "cloud-security",
    "securing-api-gateway-with-aws-waf": "cloud-security",
    "securing-aws-iam-permissions": "cloud-security",
    "securing-aws-lambda-execution-roles": "cloud-security",
    "securing-azure-with-microsoft-defender": "cloud-security",
    "securing-serverless-functions": "cloud-security",
    "implementing-ddos-mitigation-with-cloudflare": "cloud-security",

    # ─── IDENTITY & ACCESS ────────────────────────────────────────────
    "building-identity-federation-with-saml-azure-ad": "identity-access",
    "building-identity-governance-lifecycle-process": "identity-access",
    "building-role-mining-for-rbac-optimization": "identity-access",
    "configuring-identity-aware-proxy-with-google-iap": "identity-access",
    "configuring-multi-factor-authentication-with-duo": "identity-access",
    "configuring-oauth2-authorization-flow": "identity-access",
    "configuring-zscaler-private-access-for-ztna": "identity-access",
    "deploying-software-defined-perimeter": "identity-access",
    "deploying-tailscale-for-zero-trust-vpn": "identity-access",
    "implementing-beyondcorp-zero-trust-access-model": "identity-access",
    "implementing-cisa-zero-trust-maturity-model": "identity-access",
    "implementing-conditional-access-policies-azure-ad": "identity-access",
    "implementing-delinea-secret-server-for-pam": "identity-access",
    "implementing-device-posture-assessment-in-zero-trust": "identity-access",
    "implementing-google-workspace-admin-security": "identity-access",
    "implementing-google-workspace-sso-configuration": "identity-access",
    "implementing-hashicorp-vault-dynamic-secrets": "identity-access",
    "implementing-identity-governance-with-sailpoint": "identity-access",
    "implementing-identity-verification-for-zero-trust": "identity-access",
    "implementing-just-in-time-access-provisioning": "identity-access",
    "implementing-pam-for-database-access": "identity-access",
    "implementing-passwordless-auth-with-microsoft-entra": "identity-access",
    "implementing-passwordless-authentication-with-fido2": "identity-access",
    "implementing-privileged-access-management-with-cyberark": "identity-access",
    "implementing-saml-sso-with-okta": "identity-access",
    "implementing-scim-provisioning-with-okta": "identity-access",
    "implementing-zero-knowledge-proof-for-authentication": "identity-access",
    "implementing-zero-standing-privilege-with-cyberark": "identity-access",
    "implementing-zero-trust-dns-with-nextdns": "identity-access",
    "implementing-zero-trust-for-saas-applications": "identity-access",
    "implementing-zero-trust-in-cloud": "identity-access",
    "implementing-zero-trust-network-access": "identity-access",
    "implementing-zero-trust-network-access-with-zscaler": "identity-access",
    "implementing-zero-trust-with-hashicorp-boundary": "identity-access",
    "managing-cloud-identity-with-okta": "identity-access",
    "performing-access-recertification-with-saviynt": "identity-access",
    "performing-access-review-and-certification": "identity-access",
    "performing-entitlement-review-with-sailpoint-iiq": "identity-access",
    "performing-privileged-account-access-review": "identity-access",
    "performing-service-account-audit": "identity-access",
    "performing-service-account-credential-rotation": "identity-access",
    "zero-trust": "identity-access",
    "configuring-microsegmentation-for-zero-trust": "identity-access",
    "implementing-microsegmentation-with-guardicore": "identity-access",
    "hashicorp-vault": "identity-access",
    "sops-encryption": "identity-access",
    "vpn-setup": "identity-access",
    "implementing-rbac-for-kubernetes-cluster": "identity-access",
    "implementing-rbac-hardening-for-kubernetes": "identity-access",

    # ─── APPLICATION SECURITY ─────────────────────────────────────────
    "burpsuite-project-parser": "application-security",
    "dast-scanning": "application-security",
    "differential-review": "application-security",
    "fastapi-security": "application-security",
    "ffuf-web-fuzzing": "application-security",
    "firebase-apk-scanner": "application-security",
    "firebase-security": "application-security",
    "fp-check": "application-security",
    "ghost-proxy": "application-security",
    "ghost-repo-context": "application-security",
    "ghost-scan-code": "application-security",
    "ghost-scan-deps": "application-security",
    "ghost-scan-secrets": "application-security",
    "ghost-validate": "application-security",
    "graphql-security": "application-security",
    "implementing-api-abuse-detection-with-rate-limiting": "application-security",
    "implementing-api-gateway-security-controls": "application-security",
    "implementing-api-key-security-controls": "application-security",
    "implementing-api-rate-limiting-and-throttling": "application-security",
    "implementing-api-schema-validation-security": "application-security",
    "implementing-api-security-posture-management": "application-security",
    "implementing-api-security-testing-with-42crunch": "application-security",
    "implementing-api-threat-protection-with-apigee": "application-security",
    "implementing-github-advanced-security-for-code-scanning": "application-security",
    "implementing-semgrep-for-custom-sast-rules": "application-security",
    "integrating-dast-with-owasp-zap-in-pipeline": "application-security",
    "integrating-sast-into-github-actions-pipeline": "application-security",
    "llm-app-security": "application-security",
    "model-supply-chain-security": "application-security",
    "nextjs-security": "application-security",
    "openai-security-best-practices": "application-security",
    "openai-security-ownership-map": "application-security",
    "openai-security-threat-model": "application-security",
    "performing-api-fuzzing-with-restler": "application-security",
    "performing-api-rate-limiting-bypass": "application-security",
    "performing-cryptographic-audit-of-application": "application-security",
    "performing-graphql-security-assessment": "application-security",
    "performing-oauth-scope-minimization-review": "application-security",
    "performing-sca-dependency-scanning-with-snyk": "application-security",
    "performing-security-headers-audit": "application-security",
    "performing-serverless-function-security-review": "application-security",
    "performing-soap-web-service-security-testing": "application-security",
    "prompt-injection-defense": "application-security",
    "sarif-parsing": "application-security",
    "sast-scanning": "application-security",
    "sbom-supply-chain": "application-security",
    "secure-code-review": "application-security",
    "security-scan": "application-security",
    "semgrep": "application-security",
    "semgrep-rule-creator": "application-security",
    "semgrep-rule-variant-creator": "application-security",
    "spec-to-code-compliance": "application-security",
    "supply-chain-risk-auditor": "application-security",
    "supabase-security": "application-security",
    "testing-android-intents-for-vulnerabilities": "application-security",
    "testing-api-authentication-weaknesses": "application-security",
    "testing-api-for-broken-object-level-authorization": "application-security",
    "testing-api-for-mass-assignment-vulnerability": "application-security",
    "testing-api-security-with-owasp-top-10": "application-security",
    "testing-cors-misconfiguration": "application-security",
    "testing-for-broken-access-control": "application-security",
    "testing-for-business-logic-vulnerabilities": "application-security",
    "testing-for-email-header-injection": "application-security",
    "testing-for-host-header-injection": "application-security",
    "testing-for-json-web-token-vulnerabilities": "application-security",
    "testing-for-open-redirect-vulnerabilities": "application-security",
    "testing-for-sensitive-data-exposure": "application-security",
    "testing-for-xml-injection-vulnerabilities": "application-security",
    "testing-for-xss-vulnerabilities": "application-security",
    "testing-for-xss-vulnerabilities-with-burpsuite": "application-security",
    "testing-for-xxe-injection-vulnerabilities": "application-security",
    "testing-handbook-generator": "application-security",
    "testing-jwt-token-security": "application-security",
    "testing-mobile-api-authentication": "application-security",
    "testing-oauth2-implementation-flaws": "application-security",
    "testing-websocket-api-security": "application-security",
    "variant-analysis": "application-security",
    "vulnerability-verification": "application-security",
    "codeql": "application-security",
    "ai-agent-security": "application-security",
    "ai-red-teaming": "application-security",
    "ai-security-hardening": "application-security",

    # ─── NETWORK SECURITY ─────────────────────────────────────────────
    "configuring-network-segmentation-with-vlans": "network-security",
    "configuring-pfsense-firewall-rules": "network-security",
    "configuring-tls-1-3-for-secure-communications": "network-security",
    "firewall-config": "network-security",
    "implementing-bgp-security-with-rpki": "network-security",
    "implementing-network-access-control": "network-security",
    "implementing-network-access-control-with-cisco-ise": "network-security",
    "implementing-network-intrusion-prevention-with-suricata": "network-security",
    "implementing-network-policies-for-kubernetes": "network-security",
    "implementing-network-segmentation-with-firewall-zones": "network-security",
    "implementing-network-segmentation-for-ot": "network-security",
    "implementing-next-generation-firewall-with-palo-alto": "network-security",
    "performing-ssl-certificate-lifecycle-management": "network-security",
    "performing-ssl-tls-inspection-configuration": "network-security",
    "ssl-tls-management": "network-security",
    "waf-setup": "network-security",

    # ─── OT / ICS SECURITY ────────────────────────────────────────────
    "implementing-conduit-security-for-ot-remote-access": "ot-ics-security",
    "implementing-dragos-platform-for-ot-monitoring": "ot-ics-security",
    "implementing-ics-firewall-with-tofino": "ot-ics-security",
    "implementing-iec-62443-security-zones": "ot-ics-security",
    "implementing-nerc-cip-compliance-controls": "ot-ics-security",
    "implementing-ot-incident-response-playbook": "ot-ics-security",
    "implementing-ot-network-traffic-analysis-with-nozomi": "ot-ics-security",
    "implementing-patch-management-for-ot-systems": "ot-ics-security",
    "implementing-purdue-model-network-segmentation": "ot-ics-security",
    "performing-ics-asset-discovery-with-claroty": "ot-ics-security",
    "performing-oil-gas-cybersecurity-assessment": "ot-ics-security",
    "performing-ot-network-security-assessment": "ot-ics-security",
    "performing-ot-vulnerability-assessment-with-claroty": "ot-ics-security",
    "performing-ot-vulnerability-scanning-safely": "ot-ics-security",
    "performing-power-grid-cybersecurity-assessment": "ot-ics-security",
    "performing-s7comm-protocol-security-analysis": "ot-ics-security",
    "performing-scada-hmi-security-assessment": "ot-ics-security",
    "securing-historian-server-in-ot-environment": "ot-ics-security",
    "securing-remote-access-to-ot-environment": "ot-ics-security",

    # ─── CRYPTOGRAPHY ─────────────────────────────────────────────────
    "configuring-certificate-authority-with-openssl": "cryptography",
    "configuring-hsm-for-key-storage": "cryptography",
    "constant-time-analysis": "cryptography",
    "constant-time-testing": "cryptography",
    "implementing-aes-encryption-for-data-at-rest": "cryptography",
    "implementing-code-signing-for-artifacts": "cryptography",
    "implementing-digital-signatures-with-ed25519": "cryptography",
    "implementing-disk-encryption-with-bitlocker": "cryptography",
    "implementing-end-to-end-encryption-for-messaging": "cryptography",
    "implementing-envelope-encryption-with-aws-kms": "cryptography",
    "implementing-image-provenance-verification-with-cosign": "cryptography",
    "implementing-jwt-signing-and-verification": "cryptography",
    "implementing-rsa-key-pair-management": "cryptography",
    "wycheproof": "cryptography",
    "zeroize-audit": "cryptography",

    # ─── CONTAINER SECURITY ───────────────────────────────────────────
    "auditing-kubernetes-cluster-rbac": "container-security",
    "auditing-kubernetes-rbac-permissions": "container-security",
    "container-scanning": "container-security",
    "implementing-aqua-security-for-container-scanning": "container-security",
    "implementing-container-image-minimal-base-with-distroless": "container-security",
    "implementing-kubernetes-network-policy-with-calico": "container-security",
    "implementing-kubernetes-pod-security-standards": "container-security",
    "implementing-opa-gatekeeper-for-policy-enforcement": "container-security",
    "implementing-pod-security-admission-controller": "container-security",
    "implementing-policy-as-code-with-open-policy-agent": "container-security",
    "implementing-runtime-security-with-tetragon": "container-security",
    "kubernetes-hardening": "container-security",
    "performing-container-image-hardening": "container-security",
    "performing-kubernetes-cis-benchmark-with-kube-bench": "container-security",
    "performing-kubernetes-etcd-security-assessment": "container-security",
    "scanning-container-images-with-grype": "container-security",
    "scanning-containers-with-trivy-in-cicd": "container-security",
    "scanning-docker-images-with-trivy": "container-security",
    "scanning-kubernetes-manifests-with-kubesec": "container-security",
    "securing-container-registry-images": "container-security",
    "securing-container-registry-with-harbor": "container-security",
    "securing-helm-chart-deployments": "container-security",
    "securing-kubernetes-on-cloud": "container-security",

    # ─── COMPLIANCE ───────────────────────────────────────────────────
    "building-devsecops-pipeline-with-gitlab-ci": "compliance",
    "implementing-gdpr-data-protection-controls": "compliance",
    "implementing-iso-27001-information-security-management": "compliance",
    "implementing-pci-dss-compliance-controls": "compliance",
    "performing-nist-csf-maturity-assessment": "compliance",
    "performing-soc2-type2-audit-preparation": "compliance",
    "security-assessment": "compliance",
    "security-automation": "compliance",
    "guidelines-advisor": "compliance",
    "secure-workflow-guide": "compliance",
    "audit-context-building": "compliance",
    "audit-prep-assistant": "compliance",
    "code-maturity-assessor": "compliance",
    "implementing-endpoint-dlp-controls": "compliance",

    # ─── FUZZING ──────────────────────────────────────────────────────
    "address-sanitizer": "fuzzing",
    "aflpp": "fuzzing",
    "atheris": "fuzzing",
    "cargo-fuzz": "fuzzing",
    "coverage-analysis": "fuzzing",
    "fuzzing-dictionary": "fuzzing",
    "fuzzing-obstacles": "fuzzing",
    "harness-writing": "fuzzing",
    "libafl": "fuzzing",
    "libfuzzer": "fuzzing",
    "ossfuzz": "fuzzing",
    "property-based-testing": "fuzzing",
    "ruzzy": "fuzzing",
    "seatbelt-sandboxer": "fuzzing",
    "implementing-fuzz-testing-in-cicd-with-aflplusplus": "fuzzing",

    # ─── BLOCKCHAIN SECURITY ──────────────────────────────────────────
    "algorand-vulnerability-scanner": "blockchain-security",
    "cairo-vulnerability-scanner": "blockchain-security",
    "cosmos-vulnerability-scanner": "blockchain-security",
    "entry-point-analyzer": "blockchain-security",
    "scv-scan": "blockchain-security",
    "solana-vulnerability-scanner": "blockchain-security",
    "substrate-vulnerability-scanner": "blockchain-security",
    "token-integration-analyzer": "blockchain-security",
    "ton-vulnerability-scanner": "blockchain-security",

    # ─── REPORTING ────────────────────────────────────────────────────
    "gen-report": "reporting",
    "generating-security-reports": "reporting",
    "generating-threat-intelligence-reports": "reporting",
    "ghost-report": "reporting",
    "severity-rate": "reporting",
    "writing-security-reports": "reporting",
    "writing-security-skills": "reporting",

    # ─── SOCIAL ENGINEERING ───────────────────────────────────────────
    "conducting-social-engineering-penetration-test": "social-engineering",
    "conducting-social-engineering-pretext-call": "social-engineering",
    "conducting-spearphishing-simulation-campaign": "social-engineering",
    "executing-phishing-simulation-campaign": "social-engineering",
    "implementing-anti-phishing-training-program": "social-engineering",
    "implementing-dmarc-dkim-spf-email-security": "social-engineering",
    "implementing-email-sandboxing-with-proofpoint": "social-engineering",
    "implementing-google-workspace-phishing-protection": "social-engineering",
    "implementing-mimecast-targeted-attack-protection": "social-engineering",
    "implementing-proofpoint-email-security-gateway": "social-engineering",
    "performing-adversary-in-the-middle-phishing-detection": "social-engineering",
    "performing-dmarc-policy-enforcement-rollout": "social-engineering",
    "performing-phishing-simulation-with-gophish": "social-engineering",
    "security-awareness": "social-engineering",

    # ─── TOOLING ──────────────────────────────────────────────────────
    "agentic-actions-auditor": "tooling",
    "assessment-orchestrator": "tooling",
    "dispatching-parallel-agents": "tooling",
    "using-cybersecurity-mcp-tools": "tooling",
    "using-git-worktrees": "tooling",
}

def run(cmd, cwd=None):
    result = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
    return result.returncode == 0

def main():
    repo = os.path.dirname(os.path.abspath(__file__))
    skills_dir = os.path.join(repo, SKILLS_DIR)

    # Get all existing skill folders
    existing = set(os.listdir(skills_dir))
    mapped = set(MAPPING.keys())

    # Find unmapped skills
    unmapped = existing - mapped
    if unmapped:
        print(f"\n⚠️  {len(unmapped)} unmapped skills (will be left in place):")
        for s in sorted(unmapped):
            print(f"   {s}")

    # Collect all categories
    categories = set(MAPPING.values())

    # Create category dirs
    for cat in sorted(categories):
        cat_path = os.path.join(skills_dir, cat)
        os.makedirs(cat_path, exist_ok=True)

    # Move skills
    moved = 0
    skipped = 0
    for skill, category in sorted(MAPPING.items()):
        src = os.path.join(SKILLS_DIR, skill)
        dst = os.path.join(SKILLS_DIR, category, skill)
        src_abs = os.path.join(repo, src)

        if not os.path.exists(src_abs):
            skipped += 1
            continue

        print(f"  mv {skill} → {category}/")
        ok = run(f"git mv '{src}' '{dst}'", cwd=repo)
        if ok:
            moved += 1

    print(f"\n✅ Moved {moved} skills, skipped {skipped} (not found)")

    # Commit
    run("git add -A", cwd=repo)
    run("git commit -m 'chore: sort skills into cyber function folders'", cwd=repo)
    print("\n✅ Committed.")

if __name__ == "__main__":
    main()
